### ISSUE TITLE
No password set in file .ini

### ISSUE THREAD

**Issue by fritzproject** [indifferentbroccoli/projectzomboid-server-docker#10]
hello, when i try to edit password=xxx via .env file , it returns in server.ini always password= (so no password set) if i try to force password via ini file and then reload server, it return to password= (blank) it's a bug or an issue? what i missing?... also max_ram no set. maybe i miss something?
thx for your work

**Comment by thijsvanloef** [comment]
Yup, that is most definitely a bug, thanks for letting me know

**Comment by thijsvanloef** [comment]
Please update the docker container by running:

- docker compose down --rmi all
- docker compose up -d
